services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

volumes:
  db:
    driver: local
