[package]
edition.workspace = true
license.workspace = true
name = "my-book-manager"
publish.workspace = true
version = "0.1.0"

[[bin]]
name = "app"
path = "src/bin/app.rs"

[workspace]
members = ["api", "kernel", "adapter", "shared", "registry"]

[workspace.package]
edition = "2021"
license = "MIT"
publish = false

[workspace.dependencies]
adapter = {path = "./adapter"}
anyhow = "1.0.75"
api = {path = "./api"}
async-trait = "0.1.74"
axum = {version = "0.7.5", features = ["macros"]}
axum-extra = {version = "0.9.3", features = ["typed-header"]}
bcrypt = "0.15.0"
chrono = {version = "0.4.26", default-features = false, features = ["serde"]}
derive-new = "0.6.0"
garde = {version = "0.18.0", features = ["derive", "email"]}
itertools = "0.11.0"
kernel = {path = "./kernel"}
mockall = "0.11.4"
redis = {version = "0.25.3", features = ["tokio-rustls-comp"]}
registry = {path = "./registry"}
secrecy = "0.8.0"
serde = {version = "1.0.174", features = ["derive"]}
shared = {path = "./shared"}
sqlx = {version = "0.7.3", features = [
  "runtime-tokio",
  "uuid",
  "chrono",
  "macros",
  "postgres",
  "migrate",
]}
strum = {version = "0.26.2", features = ["derive"]}
thiserror = "1.0.44"
tokio = {version = "1.37.0", features = ["full"]}
tokio-stream = "0.1.14"
tower = "0.4.13"
tracing = {version = "0.1.37", features = ["log"]}
utoipa = {version = "4.1.0", features = ["axum_extras", "uuid", "chrono"]}
uuid = {version = "1.4.0", features = ["v4", "serde"]}

[dependencies]
adapter.workspace = true
anyhow.workspace = true
api.workspace = true
axum.workspace = true
opentelemetry = "0.21.0"
opentelemetry-jaeger = {version = "0.20.0", features = ["rt-tokio"]}
registry.workspace = true
shared.workspace = true
tokio.workspace = true
tower-http = {version = "0.5.0", features = ["cors", "trace"]}
tracing-opentelemetry = "0.22.0"
tracing-subscriber = {version = "0.3.18", features = ["env-filter", "json"]}
tracing.workspace = true
utoipa-redoc = {version = "2.0.0", features = ["axum"]}
utoipa.workspace = true

[profile.dev.package.sqlx-macros]
opt-level = 3
