[package]
edition.workspace = true
license.workspace = true
name = "registry"
publish.workspace = true
version = "0.1.0"

[dependencies]
adapter.workspace = true
kernel.workspace = true
mockall.workspace = true
shared.workspace = true
